### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by rainwangphy** [gxywy/rl-plotter#1]
Dear Author, 

Thanks for your code for plotting, this helps a lot. But I am little confused by the average group function. Could you provide a example of logs, which can be used to plot the figure example you showed in 2. Practical Example in README. 

Best,
Xinrun

**Comment by gxywy** [comment]
Thank you for your issue, I'm sorry that I didn't make it clear how to group different logs. 
The plotter will automatically group the different logs by the name of the folder (`exp_name` in logger). The prefix of the folder name is the group name, and the suffix of the folder name is the number of the group member, the prefix and the suffix are divided by `-`. For example, `AAA-1`, `AAA-2`, `AAA-3` is group 1, `BBB-1`, `BBB-2` is group 2. For detail, the function below decides how to group the logs, you can also modify this part as you want.
https://github.com/gxywy/rl-plotter/blob/565c9a6013f44700b04c3b67bcaf9eaff2173cb5/rl_plotter/plot_utils.py#L217 Thank you mention this problem again, and I will also add relevant notes to README.

**Comment by rainwangphy** [comment]
Thanks for your clarification. This helps a lot. 

Best,
Xinrun
