### ISSUE TITLE
Seed and Group

### ISSUE THREAD

**Issue by ShyWindddddd** [gxywy/rl-plotter#2]
请问作者大大：
RL的试验不是应该是对不同种子求std或err嘛，为什么工具里默认是对不同种子的试验分开了 要怎么画一起呢?
例如：
logs:
 -exp_env_seed0-0
   file.csv
 -exp_env_seed1-0
   file.csv

怎么对不同种子的结果求平均。
而不是只能对：
logs:
 -exp_env_seed0-0
   file.csv
 -exp_env_seed0-1
   file.csv
同一个种子的试验求平均

**Comment by gxywy** [comment]
这样设计的目的是为了防止同一个种子的多次实验结果被覆盖，可以手动的去修改文件名对不同种子的结果求平均（参考 #1 ）
之后会考虑在
https://github.com/gxywy/rl-plotter/blob/565c9a6013f44700b04c3b67bcaf9eaff2173cb5/rl_plotter/plot_utils.py#L217
调整正则表达式来兼容不同seed的文件名

**Comment by ShyWindddddd** [comment]
> 这样设计的目的是为了防止同一个种子的多次实验结果被覆盖，可以手动的去修改文件名对不同种子的结果求平均（参考 #1 ） 之后会考虑在
> 
> https://github.com/gxywy/rl-plotter/blob/565c9a6013f44700b04c3b67bcaf9eaff2173cb5/rl_plotter/plot_utils.py#L217
> 
> 
> 调整正则表达式来兼容不同seed的文件名

太棒啦 感谢感谢
