### ISSUE TITLE
Some questions about the Label；

### ISSUE THREAD

**Issue by haijime-w** [gxywy/rl-plotter#4]
Thanks for the effort in developing this wonderful tool.
I have some questions about the Label，as showing in the picture,
![202311101](https://github.com/gxywy/rl-plotter/assets/110949064/b8d38d4d-fe56-4bec-b561-11ddcc8cc3b4)
How can I remove the number of seed (is (5) in the picture) in the label?

**Comment by gxywy** [comment]
```
--no_legend_group_num  ##don't show num of group in legend
```
use this argument

**Comment by haijime-w** [comment]
Sincere thanks!
